### ISSUE TITLE
-s no longer working, needs to be updated to -itc_provider

### ISSUE THREAD

**Issue by tkuijs** [sshaw/itunes_store_transporter_web#11]
In the option.rb file for itunes_store_transporter-0.2.0 the SHORTNAME line needs to be updated. -s is not accepted and should be 
`SHORTNAME   = [ :shortname, "-itc_provider", /\w/ ]`

Perhaps I am doing something wrong here but this fixed it for me.

**Comment by sshaw** [comment]
I see they somewhat recently added the `-itc_provider"` option. The `-s` option is still valid, but only for "encoding house accounts". Ugh.

One would think that they'd still allow `-s` to function as encoding house and differentiate based on `-account_type itunes_connect`.

Would you mind providing the error message you received? 

Thanks.

**Comment by tkuijs** [comment]
This is the message I get:

Unable to find an encoding house user for username xx.  If you are an iTunes Connect user, you must specify a provider short name with the -itc_provider option. (1244)

Perhaps you just need to add a dropdown to select either one you need per account? (Encoding House / iTunes Connect)

**Comment by sshaw** [comment]
Thanks. Working on a fix.

**Comment by tkuijs** [comment]
@sshaw It works, thanks! Testing the site on my work mac, up next getting it running on a server as a service for future usage. Thanks for creating this!

**Comment by sshaw** [comment]
Fixed in [v0.2.3](https://github.com/sshaw/itunes_store_transporter_web/releases/tag/v0.2.3). Closing.
