### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by trailtreker** [sshaw/itunes_store_transporter_web#13]
Hello SSHAW.

I'm very excited about your GUI for Transporter. I am a Windows user (and not a programmer).
I have loaded Ruby (from RubyInstaller.org) and have iTMSTransporter installed along with the latest JVM. I know that Apple states that Transporter will only work with 32 bit versions of Windows. I have a 32 bit box ready to go, but I'd like to know if I need that.

I'm happy to pay you for your time to get up and running if you would be so kind. I'd also be happy to document the Windows setup instructions on your behalf if we can figure this out.

Please tell me how to get in direct contact with you.
Mark...

**Comment by sshaw** [comment]
Closing. Made email contact via help [AT] screenstaring.com.
