### ISSUE TITLE
Can't process Verify/Status or anything else.

### ISSUE THREAD

**Issue by alexbolduc1980** [sshaw/itunes_store_transporter_web#14]
Here what I get when trying Status.

[Worker(itmsworker:jobs pid: 8516)] Job StatusJob (id=8) (queue=jobs) RUNNING
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
[Worker(itmsworker:jobs pid: 8516)] Job StatusJob (id=8) (queue=jobs) FAILED (0 prior attempts) with ITunes::Store::Transporter::ExecutionError:
[Worker(itmsworker:jobs pid: 8516)] Job StatusJob (id=8) (queue=jobs) REMOVED permanently because of 1 consecutive failures
[Worker(itmsworker:jobs pid: 8516)] 1 jobs processed at 0.7004 j/s, 1 failed

**Comment by sshaw** [comment]
This is not a problem with the GUI but a problem with `iTMSTransporter`.  Try running the status command directly via `iTMSTransporter` to confirm this. 

The Transporter (JVM) is trying to allocate 2GB of memory for the heap but is unable to. I have seen cases of this on Windows, where the OS had plenty of memory but JVM could not allocate enough. 

You can try instructing the JVM to use a smaller heap size. First try directly with transporter by using the following option`-Xmx1024m` (sets to 1 GB). 

If that works, you can add a `JVMOptions` directive to the file `UnitClassPath.txt` which should exist somewhere under `itms/share/iTMSTransporter.woa/Contents/` in `iTMSTransporter`'s root directory. If you're using OS X this will be `MacOSClassPath.txt`. That file will have an example of how to set `JVMOptions`.

**Comment by alexbolduc1980** [comment]
Thanks a lot! the -Xmx1024m do the trick, I can use Provider. but if I want to use Status or Lookup I get another error.

ERROR: More than one of the following options was specified: s, itc_provider, asc_provider

If you have a clue thanks a lot!
