### ISSUE TITLE
ERROR: More than one of the following options was specified: s, itc_provider, asc_provider

### ISSUE THREAD

**Issue by alexbolduc1980** [sshaw/itunes_store_transporter_web#15]
_Originally posted by @sshaw in https://github.com/sshaw/itunes_store_transporter_web/issues/14#issuecomment-432890880_

Thanks a lot! the -Xmx1024m do the trick, I can use Provider. but if I want to use Status or Lookup I get another error.

ERROR: More than one of the following options was specified: s, itc_provider, asc_provider

If you have a clue thanks a lot!

**Comment by sshaw** [comment]
Can you provide the complete from `iTMSTransporter`? 

Though looks like you may have provided set a short name and an itc provider in the GUI's config. As you can see, Apple does not like that.

**Comment by alexbolduc1980** [comment]
Ok figure it out! You can close the ticket... In my head the shortname was like a lable name simply for the viewing/search of task, I didn't think it was for the iTMSTransporter command.

All work well and awesome! Thanks for your time!
