### ISSUE TITLE
typo in install.rb

### ISSUE THREAD

**Issue by gockelhahn** [sshaw/itunes_store_transporter_web#19]
https://github.com/sshaw/itunes_store_transporter_web/blob/439b9bcc7e012f33518fec5bf21ef8bdd4da62fa/install.rb#L111

should be:
`"username" => $config[:db_user],`

**Comment by sshaw** [comment]
Great thanks. Typing isn't my strong suite, unfortunately.

**Comment by sshaw** [comment]
Fixed in v0.2.5

**Comment by sshaw** [comment]
Ok, fix is on master and there's now a test for install script.
