### ISSUE TITLE
Where to download iTMSTransporter for Linux

### ISSUE THREAD

**Issue by jonoirwinrsa** [sshaw/itunes_store_transporter_web#20]
Hi there

My apologies since this is not a bug with the software.

I can't find where to download the iTMSTransporter bin for Linux anywhere - all the links to the itunes connect page seem to be outdated. Can you please assist me with finding it?

Many thanks

**Comment by sshaw** [comment]
Does this help? https://help.apple.com/itc/transporteruserguide/#/apdAbeb95d60

**Comment by iamswain25** [comment]
https://itunespartner.apple.com/en/books/tools
none of them exist for the linux now

**Comment by sshaw** [comment]
I'm confused. I don't think any of the programs you linked to ever existed for Linux. But, `ITMSTransporter` for Linux can be found at the link I referenced above.

**Comment by frederikbosch** [comment]
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__linux/bin/

**Comment by BerryWang1996** [comment]
> https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__linux/bin/

Thanks! Where are you found this url? I am finding iTMSTransporter for Windows

**Comment by wecail** [comment]
Anyone can share the Transporter__linux 1.11, I just get Transporter__linux 2.0.0, but this version has some problem with JVM.

**Comment by boot-vue** [comment]
> Anyone can share the Transporter__linux 1.11, I just get Transporter__linux 2.0.0, but this version has some problem with JVM.

https://github.com/codysk/itms-transproter-docker/blob/master/iTMSTransporter_installer_linux_1.10.0.sh

**Comment by filipembcruz** [comment]
I followed this steps: https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#aria-apdbb0ee90816044

But when run sh iTMSTransporter_installer_linux_3.0.0<build>.sh I added the tag --keep and works.
```
sudo sh iTMSTransporter_installer_linux_x64_3.0.0.26.sh --keep
```

The iTMSTrasporter will be available on directory /usr/local/itms/bin/.

**Comment by omar-chaabouni** [comment]
Is someone using bitbucket pipelines? home directory is "/opt/atlassian/pipelines/agent/build"
and I can't find "/usr/local" directory
