### ISSUE TITLE
Issues installing on Mac

### ISSUE THREAD

**Issue by nbeazy** [sshaw/itunes_store_transporter_web#22]
Looking to install Transporter on macOS v 10.14.2 using Ruby Version 2.3.7 and get the following errors when looking to install.

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord (~> 4.2)

    delayed_job_active_record was resolved to 4.1.1, which depends on
      activerecord (< 5.1, >= 3.0)

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    padrino_bootstrap_forms (~> 0.1.2) was resolved to 0.1.2, which depends on
      padrino (!= 0.12.0, != 0.12.1, != 0.12.2, != 0.12.3, != 0.12.4, != 0.12.5, != 0.13.0, != 0.13.1, ~> 0.11) was resolved to 0.12.6, which depends on
        padrino-gen (= 0.12.6) was resolved to 0.12.6, which depends on
          bundler (~> 1.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.0)', which is required by gem 'padrino-gen (= 0.12.6)', in any of the sources.
```

If I change the bundler to version 1.0 I get the following error:
`/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- rubygems/format (LoadError)`

Any help is appreciated.

**Comment by sshaw** [comment]
Hi, try running `ruby install.rb` with  the [`bundler-fix` branch](https://github.com/sshaw/itunes_store_transporter_web/tree/bundler-fix). Let me know if that works.

**Comment by nbeazy** [comment]
```
/itunes_store_transporter_web-bundler-fix/vendor/bundle/ruby/2.3.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require': Could not load 'active_record/connection_adapters/pg_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
```
I was attempting to install with postgresql

**Comment by sshaw** [comment]
Good to hear that solved the bundler problem. 

You [must install the underlying DB driver yourself](https://github.com/sshaw/itunes_store_transporter_web#requirements). On macOS the underlying SQLite drover should already be installed so that may be a better option unless you truly need PostgreSQL. 

Installers for macOS can be found [here](https://www.postgresql.org/download/macosx/).

**Comment by sshaw** [comment]
Without the full output from the install script I'm not 100% sure that lack of PostgreSQL is the issues but could be...

**Comment by nbeazy** [comment]
Yup that solved it.  Thanks.
