### ISSUE TITLE
Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)

### ISSUE THREAD

**Issue by radish2012** [sshaw/itunes_store_transporter_web#25]

**Comment by sshaw** [comment]
Thanks but this is not helpful. 

What operation were you performing? Can you supply the transporter log file?

**Comment by radish2012** [comment]
Providers job added to the queue.

**Comment by radish2012** [comment]
Apple forced a second validation

**Comment by sshaw** [comment]
So you provided a username and password, did you provide a shortname or itc_provider. What `iTMSTansporter` version are you using?

**Comment by radish2012** [comment]
I just provided a  username and password.

**Comment by radish2012** [comment]
i do not know where to find there version

**Comment by radish2012** [comment]
is it in appveyor.yml ? It 0.2.3b{build}

**Comment by sshaw** [comment]
You have to run the following command to determine the version: `iTMSTransporter --version`

**Comment by sshaw** [comment]
And how does one even provide an "app-specific password"? Maybe this is not an issue with this application but that you're not providing the right information. #21 is the same but the person who opened it never elaborated.

**Comment by sshaw** [comment]
Closing. As far as I can tell this is not an issue with the library. Feel free to reopen if you have evidence shows otherwise.
