### ISSUE TITLE
Can I upload ipA files?

### ISSUE THREAD

**Issue by q351941406** [sshaw/itunes_store_transporter_web#29]
Can I upload ipA files?

**Comment by sshaw** [comment]
I think you will have to update [this](https://github.com/sshaw/itunes_store_transporter_web/blob/8906d66efa8649ddb27f057b81baeb8fdf4610ea/lib/options.rb#L33-L39) then you should be okay.

**Comment by q351941406** [comment]
I only have one IPA file, can you upload successfully without specifying -assetDescription appStoreInfo. plist in your code?

**Comment by sshaw** [comment]
Hi, I see. IPA files require different arguments than itmsp directories which is what I'm familiar with. From [Apple's docs](https://help.apple.com/itc/transporteruserguide/en.lproj/static.html) for `assetFile`:

```
Specifies the directory and filename for the app source file (.pkg or .ipa). For Linux and Windows, -assetDescription is required.
```
Currently this (`assetDescription`) is not supported but, what is the `iTMSTrasporter` command you'd like to execute?

**Comment by q351941406** [comment]
OK

**Comment by sshaw** [comment]
What is the full iTMSTrasporter command you'd like to execute?

**Comment by q351941406** [comment]
I have found the solution, the problem is that I can't sign with Linux, do you understand this?
